version: '3.9'
services:
  app:
    restart: always
    image: ilhamfadhilah/gitea:${TAG_VERSION}
    depends_on:
      - postgresql
    build:
      context: ../../
      dockerfile: Dockerfile
    ports:
      - "${GITEA_SSH_PORT}:22"
      - "${GITEA_WEB_PORT}:3000"
    environment:
      VIRTUAL_PORT: 3000
      VIRTUAL_HOST: ${GITEA_HOSTNAME}
      GITEA__database__DB_TYPE: mysql
      GITEA__database__HOST: mariadb:3306
      GITEA__database__NAME: gitea
      GITEA__database__USER: gitea
      GITEA__database__PASSWD: gitea123456
      SSH_PORT: 31022
      SSH_LISTEN_PORT: 22
      ROOT_URL: http://${GITEA_HOSTNAME}:${GITEA_WEB_PORT}
      S3_HOST: https://is3.cloudhost.id
      S3_BUCKET: dev-gitea
      S3_ACCESS_KEY_ID: M2Q48SOU7S5J31XN96H2
      S3_SECRET_ACCESS_KEY: 5kw3DE9nDoCiQnLCPWpPT3mWwFVekDLl9xliS3bv
      S3_MOUNT_POINT: /mnt/gitea/git
      JUICEFS_METADATA_STORAGE: mysql://gitea:gitea123456@(mariadb:3306)/gitea_juicefs
    volumes:
      - './config/gitea:/data/gitea/conf:rw'
    cap_add:
      - SYS_ADMIN
    security_opt:
      - 'apparmor:unconfined'
    devices:
      - /dev/fuse
    shm_size: '256m'
    networks:
      default:
  postgresql:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - './volumes/gitea_pgsql/data:/var/lib/postgresql/data'
      - './config/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql'
    restart: unless-stopped
    ports:
      - 31543:5432
    networks:
      default:
  mariadb:
    image: mariadb:10.3.10
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=productzilla
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea123456
    volumes:
      - ./volumes/mariadb:/var/lib/mysql
    ports:
      - 31306:3306
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '--silent']
  prepare-mariadb:
    image: mariadb:10.3.8
    restart: on-failure
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      SQL: |-
        CREATE DATABASE IF NOT EXISTS gitea_juicefs;
        GRANT ALL PRIVILEGES ON gitea_juicefs.* to gitea@"%";
    entrypoint: /bin/bash -c
    command:
      - mysql -u root -p"productzilla" -h mariadb -e "$$SQL"
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - '8920:8080'
    depends_on:
      - postgresql
    networks:
      default:
  proxy:
    image: dannydirect/tinyproxy:latest
    ports:
      - 8882:8888
    command: ANY
    networks:
      default:

networks:
  default:
